In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load the data
train_df = pd.read_csv("../dataset/preprocessed_train.csv")
test_df = pd.read_csv("../dataset/preprocessed_test.csv")

In [4]:
test_df.head()

,amount_tsh,gps_height,longitude,latitude,population,construction_year,basin_Internal,basin_Lake Nyasa,basin_Lake Rukwa,basin_Lake Tanganyika,...,waterpoint_type_improved spring,waterpoint_type_other,funder_frequency,installer_frequency,lga_frequency,year_recorded,month_recorded,geo_cluster,pump_age,geo_cluster_source
0,3.931826,1996.0,35.290799,-4.059696,5.774552,2012.0,1,0,0,0,...,0,1,0.31,0.48,0.50,2013,2,8,1.0,0.507762
1,3.044522,1569.0,36.656709,-3.309214,5.707110,2000.0,0,0,0,0,...,0,0,15.29,0.01,2.11,2013,2,8,13.0,0.270391
2,3.931826,1567.0,34.767863,-5.004344,6.216606,2010.0,1,0,0,0,...,0,1,0.01,0.01,1.68,2013,2,8,3.0,0.507762
3,3.931826,267.0,38.058046,-9.418672,5.525453,1987.0,0,0,0,0,...,0,1,0.06,0.00,0.26,2013,1,8,26.0,0.179469
4,6.216606,1260.0,35.006123,-10.950412,4.110874,2000.0,0,0,0,0,...,0,0,0.03,0.00,1.26,2013,3,8,13.0,0.270391


In [5]:
train_df.head()

,amount_tsh,gps_height,longitude,latitude,population,construction_year,status_group,basin_Internal,basin_Lake Nyasa,basin_Lake Rukwa,...,waterpoint_type_improved spring,waterpoint_type_other,funder_frequency,installer_frequency,lga_frequency,year_recorded,month_recorded,geo_cluster,pump_age,geo_cluster_source
0,1.389293,0.388727,-0.005410,-0.927176,-0.376880,1999.0,functional,0,1,0,...,0,0,57.52,50.47,64.48,2011,3,7,12.0,0.787779
1,-0.398433,0.406220,-0.067652,0.551184,0.209470,2010.0,functional,0,0,0,...,0,0,57.52,50.47,64.48,2013,3,6,3.0,0.594938
2,-0.992374,-0.979592,0.650639,0.230180,0.138885,2009.0,functional,0,0,0,...,0,0,57.52,50.47,64.48,2013,2,9,4.0,0.570156
3,-0.697497,-1.801749,0.917341,-1.176286,-0.766338,1986.0,non functional,0,0,0,...,0,0,1.78,50.47,64.48,2013,1,8,27.0,0.405571
4,0.000000,0.000000,-0.995565,0.612956,0.000000,1986.0,functional,0,0,0,...,0,0,57.52,50.47,1.30,2011,7,1,25.0,0.646602


In [6]:
test_df.isnull().sum()

amount_tsh            0
gps_height            0
longitude             0
latitude              0
population            0
                     ..
year_recorded         0
month_recorded        0
geo_cluster           0
pump_age              0
geo_cluster_source    0
Length: 113, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

X = train_df.drop(columns=["status_group"])
y = train_df["status_group"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [12]:
# lets train a random forest model
from sklearn.ensemble import RandomForestClassifier


rf_model = RandomForestClassifier(
    n_estimators = 500, 
    max_depth = None,
    min_samples_split = 5,
    min_samples_leaf = 2,
    max_features = "sqrt",
    bootstrap = True,
    random_state = 42,
    n_jobs = -1
)

rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",500
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",5
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",2
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [13]:
rf_model_preds = rf_model.predict(X_val)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_val, rf_model_preds))
print(confusion_matrix(y_val, rf_model_preds))
print(accuracy_score(y_val, rf_model_preds))

                         precision    recall  f1-score   support

             functional       0.79      0.92      0.85      6452
functional needs repair       0.65      0.25      0.36       863
         non functional       0.85      0.76      0.81      4565

               accuracy                           0.81     11880
              macro avg       0.77      0.64      0.67     11880
           weighted avg       0.81      0.81      0.80     11880

[[5930   76  446]
 [ 506  212  145]
 [1046   38 3481]]
0.810016835016835


In [14]:
rf_model_preds = rf_model.predict(test_df)
rf_model_preds

array(['non functional', 'functional', 'non functional', ...,
       'functional', 'functional', 'non functional'],
      shape=(14850,), dtype=object)

In [15]:
# load test_ids
test_ids = pd.read_csv("../dataset/test_ids.csv")
submission_df = pd.DataFrame({
    "id": test_ids["id"],
    "status_group": rf_model_preds
})

submission_df.to_csv("../submissions/submission_baseline_without_class_weights.csv", index=False)

In [ ]:
# this only scored a 0.7416 on the leaderboard which is not bad
# for now lets move on to the xgboost model 

In [16]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=0.1,       # L1
    reg_lambda=1.0,      # L2
    objective='multi:softmax',
    num_class=3,
    eval_metric='mlogloss',
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1,
    device='cuda'
)

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y_train)
y_val_encoded = le.transform(y_val)


xgb_model.fit(X_train, y_encoded, 
              eval_set=[(X_val, y_val_encoded)], 
              verbose=100)

[0]	validation_0-mlogloss:0.87151
[100]	validation_0-mlogloss:0.57251
[200]	validation_0-mlogloss:0.54028
[300]	validation_0-mlogloss:0.52267
[400]	validation_0-mlogloss:0.51098
[500]	validation_0-mlogloss:0.50242
[600]	validation_0-mlogloss:0.49629
[700]	validation_0-mlogloss:0.49209
[800]	validation_0-mlogloss:0.48848
[900]	validation_0-mlogloss:0.48546
[999]	validation_0-mlogloss:0.48311


,"objective objective: str | xgboost.sklearn._SklObjWProto | typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]] | NoneSpecify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softmax'
,"base_score base_score: float | typing.List[float] | NoneThe initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.List[xgboost.callback.TrainingCallback] | NoneList of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: float | NoneSubsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: float | NoneSubsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: float | NoneSubsample ratio of columns when constructing each tree.,0.8
,"device device: str | None.. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",'cuda'
,"early_stopping_rounds early_stopping_rounds: int | None.. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",50
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: str | typing.List[str | typing.Callable] | typing.Callable | None.. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) reg = xgb.XGBRegressor( tree_method=

In [19]:
xgb_model_preds = xgb_model.predict(X_val)
print(classification_report(y_val_encoded, xgb_model_preds))
print(confusion_matrix(y_val_encoded, xgb_model_preds))
print(accuracy_score(y_val_encoded, xgb_model_preds))

              precision    recall  f1-score   support

           0       0.79      0.91      0.84      6452
           1       0.63      0.27      0.38       863
           2       0.85      0.75      0.80      4565

    accuracy                           0.80     11880
   macro avg       0.75      0.64      0.67     11880
weighted avg       0.80      0.80      0.79     11880

[[5860   97  495]
 [ 497  231  135]
 [1087   40 3438]]
0.8021043771043771


c:\Users\omaro\OneDrive\Desktop\Study\Kaggle Competitions\pump_it_up_competition\venv\Lib\site-packages\xgboost\core.py:751: UserWarning: [04:49:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)


In [20]:
xgb_model_preds_test = xgb_model.predict(test_df)

submission_df = pd.DataFrame({
    "id": test_ids["id"],
    "status_group": le.inverse_transform(xgb_model_preds_test)
})
submission_df.to_csv("../submissions/submission_xgboost.csv", index=False)