In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
# load the data
train_df = pd.read_csv("../dataset/train_clean.csv")
test_df = pd.read_csv("../dataset/test_clean.csv")

In [20]:
test_df.head()

,amount_tsh,gps_height,longitude,latitude,population,construction_year,is_tsh_missing,is_year_missing,is_pop_missing,is_coord_missing,...,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other,geo_cluster,pump_age,geo_source_te,geo_source_freq
0,3.931826,1996.0,35.290799,-4.059696,5.774552,2012.0,1,0,0,0,...,0,0,0,0,0,1,9,1.0,0.640050,0.523685
1,3.044522,1569.0,36.656709,-3.309214,5.707110,2000.0,1,0,0,0,...,1,0,0,0,0,0,0,13.0,0.675847,9.818672
2,3.931826,1567.0,34.767863,-5.004344,6.216606,2010.0,1,0,0,0,...,0,0,0,0,0,1,9,3.0,0.640050,0.523685
3,3.931826,267.0,38.058046,-9.418672,5.525453,1987.0,1,0,0,0,...,0,0,0,0,0,1,3,26.0,1.605582,1.731402
4,6.216606,1260.0,35.006123,-10.950412,4.110874,2000.0,0,0,0,0,...,1,0,0,0,0,0,2,13.0,0.803993,1.465295


In [21]:
train_df.head()

,amount_tsh,gps_height,longitude,latitude,population,construction_year,status_group,is_tsh_missing,is_year_missing,is_pop_missing,...,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other,geo_cluster,pump_age,geo_source_te,geo_source_freq
0,8.699681,1390.0,34.938093,-9.856322,4.700480,1999.0,functional,0,0,0,...,1,0,0,0,0,0,2,12.0,0.810144,1.465295
1,4.615121,1399.0,34.698766,-2.147466,5.638355,2010.0,functional,1,0,0,...,1,0,0,0,0,0,6,3.0,0.669483,0.564625
2,3.258097,686.0,37.460664,-3.821329,5.525453,2009.0,functional,0,0,0,...,0,1,0,0,0,0,0,4.0,0.812285,0.049469
3,3.931826,263.0,38.486161,-11.155298,4.077537,1986.0,non functional,1,0,0,...,0,1,0,0,0,0,3,27.0,1.185000,2.725893
4,5.525453,1189.0,31.130847,-1.825359,5.303305,1986.0,functional,1,1,1,...,1,0,0,0,0,0,11,25.0,0.607714,0.639681


In [22]:
# because some tree models do not accept spaces in column names
train_df.columns = train_df.columns.str.replace(" ", "_")
test_df.columns = test_df.columns.str.replace(" ", "_")

In [23]:
set(train_df.columns.tolist())-(set(test_df.columns.tolist()))

{'status_group'}

In [24]:
y = train_df["status_group"]
X = train_df.drop(["status_group"], axis=1)

In [25]:
test_df.isnull().sum()

amount_tsh               0
gps_height               0
longitude                0
latitude                 0
population               0
                        ..
waterpoint_type_other    0
geo_cluster              0
pump_age                 0
geo_source_te            0
geo_source_freq          0
Length: 138, dtype: int64

In [26]:
train_df.isnull().sum()

amount_tsh               0
gps_height               0
longitude                0
latitude                 0
population               0
                        ..
waterpoint_type_other    0
geo_cluster              0
pump_age                 0
geo_source_te            0
geo_source_freq          0
Length: 139, dtype: int64

In [27]:
X.shape

(58623, 138)

In [28]:
test_df.shape

(14850, 138)

In [29]:
from sklearn.model_selection import train_test_split

X = train_df.drop(columns=["status_group"])
y = train_df["status_group"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# lets train a random forest model
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators = 500, 
    max_depth = None,
    min_samples_split = 5,
    min_samples_leaf = 2,
    max_features = "sqrt",
    bootstrap = True,
    random_state = 42,
    n_jobs = -1,
    class_weight = "balanced"
)

rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",500
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",5
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",2
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [31]:
rf_model_preds = rf_model.predict(X_val)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_val, rf_model_preds))
print(confusion_matrix(y_val, rf_model_preds))
print(accuracy_score(y_val, rf_model_preds))

                         precision    recall  f1-score   support

             functional       0.79      0.91      0.85      6364
functional needs repair       0.63      0.24      0.34       838
         non functional       0.84      0.77      0.80      4523

               accuracy                           0.81     11725
              macro avg       0.75      0.64      0.67     11725
           weighted avg       0.80      0.81      0.79     11725

[[5784   71  509]
 [ 509  199  130]
 [1003   48 3472]]
0.8063965884861407


In [32]:
rf_model_preds = rf_model.predict(test_df)
rf_model_preds

array(['functional', 'functional', 'functional', ..., 'functional',
       'functional', 'non functional'], shape=(14850,), dtype=object)

In [ ]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=0.1,       # L1
    reg_lambda=1.0,      # L2
    objective='multi:softmax',
    num_class=3,
    eval_metric='mlogloss',
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1,
    device='cuda',
    class_weight='balanced'
)

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y_train)
y_val_encoded = le.transform(y_val)


xgb_model.fit(X_train, y_encoded, 
              eval_set=[(X_val, y_val_encoded)])

[0]	validation_0-mlogloss:0.86957
[1]	validation_0-mlogloss:0.85509
[2]	validation_0-mlogloss:0.84046
[3]	validation_0-mlogloss:0.82703
[4]	validation_0-mlogloss:0.81416
[5]	validation_0-mlogloss:0.80278
[6]	validation_0-mlogloss:0.79144
[7]	validation_0-mlogloss:0.78110
[8]	validation_0-mlogloss:0.77142
[9]	validation_0-mlogloss:0.76263
[10]	validation_0-mlogloss:0.75439
[11]	validation_0-mlogloss:0.74657
[12]	validation_0-mlogloss:0.73958
[13]	validation_0-mlogloss:0.73240
[14]	validation_0-mlogloss:0.72610
[15]	validation_0-mlogloss:0.72027
[16]	validation_0-mlogloss:0.71456
[17]	validation_0-mlogloss:0.70914
[18]	validation_0-mlogloss:0.70400
[19]	validation_0-mlogloss:0.69925
[20]	validation_0-mlogloss:0.69475
[21]	validation_0-mlogloss:0.69059
[22]	validation_0-mlogloss:0.68657
[23]	validation_0-mlogloss:0.68280
[24]	validation_0-mlogloss:0.67922
[25]	validation_0-mlogloss:0.67566
[26]	validation_0-mlogloss:0.67223
[27]	validation_0-mlogloss:0.66894
[28]	validation_0-mlogloss:0.6

,"objective objective: str | xgboost.sklearn._SklObjWProto | typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]] | NoneSpecify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softmax'
,"base_score base_score: float | typing.List[float] | NoneThe initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.List[xgboost.callback.TrainingCallback] | NoneList of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: float | NoneSubsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: float | NoneSubsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: float | NoneSubsample ratio of columns when constructing each tree.,0.8
,"device device: str | None.. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",'cuda'
,"early_stopping_rounds early_stopping_rounds: int | None.. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",50
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: str | typing.List[str | typing.Callable] | typing.Callable | None.. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) reg = xgb.XGBRegressor( tree_method=

In [35]:
xgb_model_preds = xgb_model.predict(X_val)
print(classification_report(y_val_encoded, xgb_model_preds))
print(confusion_matrix(y_val_encoded, xgb_model_preds))
print(accuracy_score(y_val_encoded, xgb_model_preds))

c:\Users\omaro\OneDrive\Desktop\Study\Kaggle Competitions\pump_it_up_competition\venv\Lib\site-packages\xgboost\core.py:751: UserWarning: [03:12:37] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)


              precision    recall  f1-score   support

           0       0.79      0.90      0.84      6364
           1       0.60      0.25      0.35       838
           2       0.84      0.76      0.80      4523

    accuracy                           0.80     11725
   macro avg       0.74      0.64      0.66     11725
weighted avg       0.79      0.80      0.79     11725

[[5753   85  526]
 [ 506  208  124]
 [1045   53 3425]]
0.8005117270788913


In [36]:
# now let me try the lgbm model
from lightgbm import LGBMClassifier

lgbm_model = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,

    num_leaves=64,
    max_depth=-1,

    min_data_in_leaf=20,   # ONLY this (not min_child_samples)
    min_gain_to_split=0.0, # ONLY this (not min_split_gain)

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=42
)

lgbm_model.fit(X_train, y_encoded,
              eval_set=[(X_val, y_val_encoded)])

[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001703 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1804
[LightGBM] [Info] Number of data points in the train set: 46898, number of used features: 135
[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to

,boosting_type,'gbdt'
,num_leaves,64
,max_depth,-1
,learning_rate,0.05
,n_estimators,500
,subsample_for_bin,200000
,objective,None
,class_weight,None
,min_split_gain,0.0
,min_child_weight,0.001
,min_child_samples,20


In [37]:
lgbm_preds = lgbm_model.predict(X_val)
print(classification_report(y_val_encoded, lgbm_preds)) #type: ignore
print(confusion_matrix(y_val_encoded, lgbm_preds))  #type: ignore
print(accuracy_score(y_val_encoded, lgbm_preds))    #type: ignore

[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
              precision    recall  f1-score   support

           0       0.79      0.90      0.84      6364
           1       0.55      0.25      0.34       838
           2       0.84      0.76      0.80      4523

    accuracy                           0.80     11725
   macro avg       0.73      0.64      0.66     11725
weighted avg       0.79      0.80      0.79     11725

[[5715  118  531]
 [ 509  210  119]
 [1037   54 3432]]
0.7980383795309168


In [38]:
from sklearn.neural_network import MLPClassifier

mlp_model = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation='relu',
    solver='adam',
    max_iter=200,
    random_state=42
)

mlp_model.fit(X_train, y_encoded)

,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(128, ...)"
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'adam'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",0.0001
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.001
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",200
,"shuffle shuffle: bool, default=TrueWhether to shuffle samples in each iteration. Only used whensolver='sgd' or 'adam'.",True
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary `.",42


In [39]:
mlp_preds = mlp_model.predict(X_val)
print(classification_report(y_val_encoded, mlp_preds)) #type: ignore
print(confusion_matrix(y_val_encoded, mlp_preds))  #type: ignore
print(accuracy_score(y_val_encoded, mlp_preds))    #type: ignore

              precision    recall  f1-score   support

           0       0.71      0.93      0.80      6364
           1       0.10      0.00      0.00       838
           2       0.82      0.61      0.70      4523

    accuracy                           0.74     11725
   macro avg       0.54      0.51      0.50     11725
weighted avg       0.71      0.74      0.70     11725

[[5897    2  465]
 [ 701    1  136]
 [1765    7 2751]]
0.7376545842217485


In [115]:
test_ids = pd.read_csv('../dataset/test_ids.csv')['id']

In [117]:
# lets create a submission file for the lgbm model
lgbm_test_preds = lgbm_model.predict(test_df)
submission_df = pd.DataFrame({
    "id": test_ids,
    "status_group": le.inverse_transform(lgbm_test_preds)   #type: ignore
})

[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0


In [ ]:
submission_df.to_csv("../submissions/lgbm_submission.csv", index=False)